/* Retro arcade collection: ICBM, Asteroids, Computer Space, Lunar Lander, Moon Patrol. */
(()=>{'use strict';
const C=document.getElementById('game'),c=C.getContext('2d'),W=960,H=640,ID=window.GAME_ID||'icbm';
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),d=(a,b,x,y)=>Math.hypot(a-x,b-y),wrap=o=>{if(o.x<0)o.x+=W;if(o.x>W)o.x-=W;if(o.y<0)o.y+=H;if(o.y>H)o.y-=H},line=(x,y,a,b)=>{c.beginPath();c.moveTo(x,y);c.lineTo(a,b);c.stroke()},txt=(s,x,y,n=18,align='left')=>{c.textAlign=align;c.font=`bold ${n}px monospace`;c.fillText(s,x,y)};
let state='title',game,last=0,held=new Set(),high=0,audio=null;
try{high=Number(localStorage.getItem('arcade-'+ID)||0)}catch(e){}
function sound(f=360,t=.06){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.022,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+t);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+t)}catch(e){}}
function score(v){game.score+=v;if(game.score>high){high=game.score;try{localStorage.setItem('arcade-'+ID,high)}catch(e){}}}
function spark(arr,x,y,n=12){for(let i=0;i<n;i++){let a=rnd(0,7),s=rnd(25,170);arr.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:rnd(.25,.9)})}sound(90,.12)}
function stepParticles(arr,dt){for(const p of arr){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt}return arr.filter(p=>p.t>0)}
function drawParticles(arr){c.strokeStyle='#ffb65c';for(const p of arr){c.globalAlpha=clamp(p.t,0,1);line(p.x,p.y,p.x-p.vx*.025,p.y-p.vy*.025)}c.globalAlpha=1}
function hud(g,label,extra=''){c.fillStyle='#e8f5ff';txt('SCORE '+String(g.score).padStart(5,'0'),18,30);txt(label,W/2,30,18,'center');txt('HIGH '+String(high).padStart(5,'0'),W-18,30,18,'right');c.font='14px monospace';txt(extra,18,54,14)}
function ground(){c.strokeStyle='#96bad5';line(0,548,W,548);c.fillStyle='#17212b';c.fillRect(0,549,W,91)}
function makeICBM(){let g={score:0,wave:1,cities:[190,285,380,580,675,770].map(x=>({x,ok:true})),bases:[72,480,888].map(x=>({x,ammo:12})),en:[],own:[],boom:[],fx:[],spawn:1,count:0,total:12,rest:0};
function next(){g.wave++;g.total=10+g.wave*3;g.count=0;g.spawn=1;g.bases.forEach(b=>b.ammo=12);g.rest=0}
function fire(x,y){if(state!=='playing')return;let base=g.bases.filter(b=>b.ammo>0).sort((a,b)=>Math.abs(a.x-x)-Math.abs(b.x-x))[0];if(!base)return;base.ammo--;g.own.push({x:base.x,y:527,tx:x,ty:clamp(y,45,520),v:510});sound(650)}
g.pointer=fire;g.key=k=>{if(k==='Space')fire(W/2,220)};
g.update=dt=>{g.fx=stepParticles(g.fx,dt);if(g.rest>0){g.rest-=dt;if(g.rest<=0)next();return}g.spawn-=dt;if(g.count<g.total&&g.spawn<=0){let targets=g.cities.filter(z=>z.ok);if(!targets.length){state='gameover';return}let target=targets[Math.floor(rnd(0,targets.length))];let x=rnd(20,940);g.en.push({x,y:-8,tx:target.x,ty:543,s:45+g.wave*8,split:g.wave>=3&&Math.random()<.16});g.count++;g.spawn=rnd(.45,1.1)*Math.max(.48,1-g.wave*.035)}
for(const m of g.en){let a=Math.atan2(m.ty-m.y,m.tx-m.x);m.x+=Math.cos(a)*m.s*dt;m.y+=Math.sin(a)*m.s*dt;if(m.split&&m.y>230){m.split=false;for(const off of [-90,90])g.en.push({x:m.x,y:m.y,tx:clamp(m.tx+off,60,900),ty:543,s:m.s*1.25,split:false})}if(m.y>=543){m.dead=true;let city=g.cities.find(z=>z.ok&&Math.abs(z.x-m.tx)<45);if(city){city.ok=false;spark(g.fx,city.x,535,22)}}for(const e of g.boom)if(d(m.x,m.y,e.x,e.y)<e.r){m.dead=true;score(25);spark(g.fx,m.x,m.y,5);break}}g.en=g.en.filter(m=>!m.dead);
for(const m of g.own){let a=Math.atan2(m.ty-m.y,m.tx-m.x),v=Math.min(m.v*dt,d(m.x,m.y,m.tx,m.ty));m.x+=Math.cos(a)*v;m.y+=Math.sin(a)*v;if(d(m.x,m.y,m.tx,m.ty)<3){m.dead=true;g.boom.push({x:m.tx,y:m.ty,r:1,phase:1})}}g.own=g.own.filter(m=>!m.dead);
for(const e of g.boom){e.r+=(e.phase?108:-64)*dt;if(e.r>=72)e.phase=0;if(e.r<=0)e.dead=true}g.boom=g.boom.filter(e=>!e.dead);
if(!g.cities.some(z=>z.ok)){state='gameover'}else if(g.count>=g.total&&!g.en.length&&!g.own.length&&!g.boom.length){score(g.cities.filter(z=>z.ok).length*100+g.bases.reduce((s,b)=>s+b.ammo*5,0));g.rest=2}};
g.draw=()=>{ground();c.fillStyle='#a5e7ff';for(const z of g.cities){if(z.ok){c.fillRect(z.x-18,517,12,30);c.fillRect(z.x-3,505,15,42);c.fillRect(z.x+14,523,12,24)}else c.fillRect(z.x-18,540,40,6)}for(const b of g.bases){c.strokeStyle='#b6ef9d';c.beginPath();c.moveTo(b.x-28,547);c.lineTo(b.x,519);c.lineTo(b.x+28,547);c.stroke();txt(String(b.ammo),b.x,570,15,'center')}for(const m of g.en){c.strokeStyle='#ff6856';line(m.x,m.y-14,m.x,m.y);c.fillStyle='#ffddbb';c.fillRect(m.x-2,m.y-2,4,4)}for(const m of g.own){c.strokeStyle='#79fbff';line(m.x,m.y+12,m.x,m.y);c.fillStyle='#fff';c.fillRect(m.x-2,m.y-2,4,4)}for(const e of g.boom){let gr=c.createRadialGradient(e.x,e.y,0,e.x,e.y,e.r);gr.addColorStop(0,'#fff9a4');gr.addColorStop(.55,'#ff9025');gr.addColorStop(1,'#ff4d0000');c.fillStyle=gr;c.beginPath();c.arc(e.x,e.y,e.r,0,7);c.fill()}drawParticles(g.fx);hud(g,'ICBM · WAVE '+g.wave,'CITIES '+g.cities.filter(z=>z.ok).length+'/6   ENEMY '+g.count+'/'+g.total);if(g.rest>0)txt('WAVE CLEAR!',W/2,180,34,'center')};return g}
function makeAsteroids(){let g={score:0,lives:3,wave:1,ship:{x:480,y:320,vx:0,vy:0,a:-Math.PI/2,inv:2},rocks:[],shots:[],ufos:[],bad:[],fx:[],reload:0,ufot:8,wait:0};
function rock(x,y,n){let a=rnd(0,7),v=(40+g.wave*5)*(4-n)/2;g.rocks.push({x,y,n,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:n===3?45:n===2?27:14,a:0,spin:rnd(-1,1),shape:Array.from({length:11},()=>rnd(.72,1.18))})}function wave(){for(let i=0;i<Math.min(4+g.wave,12);i++){let x,y;do{x=rnd(35,925);y=rnd(50,590)}while(d(x,y,g.ship.x,g.ship.y)<170);rock(x,y,3)}g.wait=0}wave();
function shoot(){if(state!=='playing'||g.reload>0||g.shots.length>=5)return;let s=g.ship;g.shots.push({x:s.x+Math.cos(s.a)*18,y:s.y+Math.sin(s.a)*18,vx:Math.cos(s.a)*490+s.vx,vy:Math.sin(s.a)*490+s.vy,t:1});g.reload=.16;sound(710)}
function hit(){if(g.ship.inv>0)return;g.lives--;spark(g.fx,g.ship.x,g.ship.y,24);Object.assign(g.ship,{x:480,y:320,vx:0,vy:0,a:-Math.PI/2,inv:2.2});if(g.lives<=0)state='gameover'}
g.key=k=>{if(k==='Space')shoot();if(k==='KeyH'){g.ship.x=rnd(35,925);g.ship.y=rnd(50,590);g.ship.inv=.65}};g.pointer=()=>shoot();
g.update=dt=>{let s=g.ship;g.reload=Math.max(0,g.reload-dt);s.inv=Math.max(0,s.inv-dt);if(held.has('ArrowLeft'))s.a-=4*dt;if(held.has('ArrowRight'))s.a+=4*dt;if(held.has('ArrowUp')){s.vx+=Math.cos(s.a)*225*dt;s.vy+=Math.sin(s.a)*225*dt}let v=d(s.vx,s.vy,0,0);if(v>350){s.vx*=350/v;s.vy*=350/v}s.x+=s.vx*dt;s.y+=s.vy*dt;wrap(s);if(held.has('Space'))shoot();
for(const r of g.rocks){r.x+=r.vx*dt;r.y+=r.vy*dt;r.a+=r.spin*dt;wrap(r);if(s.inv<=0&&d(s.x,s.y,r.x,r.y)<r.r+9)hit()}for(const b of g.shots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.t-=dt;wrap(b);for(const r of g.rocks){if(!r.dead&&d(b.x,b.y,r.x,r.y)<r.r){r.dead=b.dead=true;score(r.n===3?20:r.n===2?50:100);spark(g.fx,r.x,r.y,9);if(r.n>1){rock(r.x,r.y,r.n-1);rock(r.x,r.y,r.n-1)}break}}}g.rocks=g.rocks.filter(r=>!r.dead);g.shots=g.shots.filter(b=>!b.dead&&b.t>0);
g.ufot-=dt;if(g.ufot<=0&&!g.ufos.length){g.ufos.push({x:-30,y:rnd(80,550),vy:rnd(-30,30),t:1});g.ufot=rnd(8,14)}for(const u of g.ufos){u.x+=125*dt;u.y+=u.vy*dt;u.t-=dt;for(const b of g.shots)if(d(u.x,u.y,b.x,b.y)<22){u.dead=b.dead=true;score(200);spark(g.fx,u.x,u.y,15)}if(u.t<0){u.t=1;let a=Math.atan2(s.y-u.y,s.x-u.x)+rnd(-.4,.4);g.bad.push({x:u.x,y:u.y,vx:Math.cos(a)*220,vy:Math.sin(a)*220,t:2.2})}if(u.x>990)u.dead=true}g.ufos=g.ufos.filter(u=>!u.dead);
for(const b of g.bad){b.x+=b.vx*dt;b.y+=b.vy*dt;b.t-=dt;wrap(b);if(s.inv<=0&&d(s.x,s.y,b.x,b.y)<14){b.t=0;hit()}}g.bad=g.bad.filter(b=>b.t>0);g.fx=stepParticles(g.fx,dt);if(!g.rocks.length){g.wait+=dt;if(g.wait>2){g.wave++;wave()}}};
g.draw=()=>{c.strokeStyle='#fff';c.lineWidth=2;for(const r of g.rocks){c.save();c.translate(r.x,r.y);c.rotate(r.a);c.beginPath();r.shape.forEach((m,i)=>{let a=i*7/r.shape.length,x=Math.cos(a)*r.r*m,y=Math.sin(a)*r.r*m;i?c.lineTo(x,y):c.moveTo(x,y)});c.closePath();c.stroke();c.restore()}for(const u of g.ufos){c.beginPath();c.moveTo(u.x-20,u.y);c.lineTo(u.x-9,u.y-9);c.lineTo(u.x+9,u.y-9);c.lineTo(u.x+20,u.y);c.lineTo(u.x+11,u.y+6);c.lineTo(u.x-11,u.y+6);c.closePath();c.stroke()}for(const b of [...g.shots,...g.bad]){c.fillStyle='#fff';c.fillRect(b.x-2,b.y-2,4,4)}if(Math.floor(g.ship.inv*12)%2===0){let s=g.ship;c.save();c.translate(s.x,s.y);c.rotate(s.a);c.beginPath();c.moveTo(18,0);c.lineTo(-12,-11);c.lineTo(-7,0);c.lineTo(-12,11);c.closePath();c.stroke();if(held.has('ArrowUp')){c.beginPath();c.moveTo(-10,-6);c.lineTo(-rnd(18,29),0);c.lineTo(-10,6);c.stroke()}c.restore()}drawParticles(g.fx);hud(g,'ASTEROIDS · WAVE '+g.wave,'LIVES '+g.lives+'  ← → ROTATE · ↑ THRUST · SPACE FIRE · H HYPERSPACE')};return g}
function makeComputer(){let g={score:0,enemy:0,round:1,time:99,ship:{x:320,y:320,vx:0,vy:0,a:-Math.PI/2,inv:2},ufos:[],bul:[],bad:[],fx:[],reload:0,resp:0,reverse:false};
function initU(){g.ufos=[{x:630,y:230,phase:0,t:1},{x:630,y:340,phase:3,t:1}]}initU();
function shoot(){if(state!=='playing'||g.bul.length||g.reload>0)return;let s=g.ship;g.bul.push({x:s.x+Math.cos(s.a)*18,y:s.y+Math.sin(s.a)*18,a:s.a,t:2});g.reload=.18;sound(720)}
function hit(){if(g.ship.inv>0)return;g.enemy++;spark(g.fx,g.ship.x,g.ship.y,17);Object.assign(g.ship,{x:320,y:320,vx:0,vy:0,a:-Math.PI/2,inv:2.2})}
g.key=k=>{if(k==='Space')shoot()};g.pointer=()=>shoot();
g.update=dt=>{let s=g.ship;g.time-=dt;if(g.time<=0){if(g.score>g.enemy){g.round++;g.time=99;g.score=0;g.enemy=0;g.reverse=!g.reverse;initU();Object.assign(s,{x:320,y:320,vx:0,vy:0,a:-Math.PI/2,inv:2})}else state='gameover'}g.reload=Math.max(0,g.reload-dt);s.inv=Math.max(0,s.inv-dt);let dir=(held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0);s.a+=dir*3.5*dt;if(held.has('ArrowUp')){s.vx+=Math.cos(s.a)*130*dt;s.vy+=Math.sin(s.a)*130*dt}let v=d(s.vx,s.vy,0,0);if(v>235){s.vx*=235/v;s.vy*=235/v}s.x+=s.vx*dt;s.y+=s.vy*dt;wrap(s);if(held.has('Space'))shoot();
for(const b of g.bul){b.a+=dir*2.8*dt;b.x+=Math.cos(b.a)*370*dt;b.y+=Math.sin(b.a)*370*dt;b.t-=dt;wrap(b)}g.bul=g.bul.filter(b=>b.t>0&&!b.dead);
for(const u of g.ufos){u.phase+=dt;u.x+=75*dt;u.y+=Math.sin(u.phase*2)*35*dt;wrap(u);u.t-=dt;if(u.t<=0){u.t=rnd(1,2);let a=Math.atan2(s.y-u.y,s.x-u.x)+rnd(-.3,.3);g.bad.push({x:u.x,y:u.y,vx:Math.cos(a)*210,vy:Math.sin(a)*210,t:3})}for(const b of g.bul)if(d(u.x,u.y,b.x,b.y)<24){b.dead=true;score(1);spark(g.fx,u.x,u.y);u.x=rand(580,900);u.y=rand(130,470);u.t=1}if(s.inv<=0&&d(s.x,s.y,u.x,u.y)<30)hit()}g.bul=g.bul.filter(b=>!b.dead);for(const b of g.bad){b.x+=b.vx*dt;b.y+=b.vy*dt;b.t-=dt;wrap(b);if(s.inv<=0&&d(s.x,s.y,b.x,b.y)<14){b.t=0;hit()}}g.bad=g.bad.filter(b=>b.t>0);g.fx=stepParticles(g.fx,dt)};
g.draw=()=>{if(g.reverse){c.fillStyle='#f4f4f4';c.fillRect(0,0,W,H);c.strokeStyle='#121212';c.fillStyle='#111'}else{c.strokeStyle='#fff';c.fillStyle='#fff'}c.lineWidth=2;for(const u of g.ufos){c.beginPath();c.moveTo(u.x-23,u.y);c.lineTo(u.x-11,u.y-8);c.lineTo(u.x+11,u.y-8);c.lineTo(u.x+23,u.y);c.lineTo(u.x+10,u.y+6);c.lineTo(u.x-10,u.y+6);c.closePath();c.stroke();line(u.x-8,u.y-8,u.x-4,u.y-14);line(u.x-4,u.y-14,u.x+5,u.y-14)}for(const b of [...g.bul,...g.bad])c.fillRect(b.x-2,b.y-2,4,4);if(Math.floor(g.ship.inv*10)%2===0){let s=g.ship;c.save();c.translate(s.x,s.y);c.rotate(s.a);c.beginPath();c.moveTo(20,0);c.lineTo(-11,-10);c.lineTo(-7,0);c.lineTo(-11,10);c.closePath();c.stroke();c.restore()}if(g.reverse){c.fillStyle='#111';c.strokeStyle='#111'}drawParticles(g.fx);hud(g,'COMPUTER SPACE · ROUND '+g.round,'PLAYER '+g.score+'   SAUCERS '+g.enemy+'   TIME '+Math.ceil(g.time))};return g}
function makeLunar(){let g={score:0,mission:1,fuel:1600,ship:{x:1600,y:110,vx:0,vy:0,a:0,omega:0,thrust:0},pts:[],pads:[],fx:[],cameraX:1120,cameraY:0,zoom:1,rest:0,msg:''};const GW=3200,GY=12.5;
function generate(){g.pts=[];let y=515;for(let x=0;x<=GW;x+=25){y=clamp(y+rnd(-27,27),410,550);g.pts.push({x,y})}g.pads=[];let sizes=[230,200,150,125,85];for(let i=0;i<5;i++){let xx=[380,950,1590,2260,2800][i],w=sizes[i],p={x:xx,l:xx-w/2,r:xx+w/2,y:0,m:i<2?1:i<4?2:5};p.y=height(xx);g.pads.push(p);for(const z of g.pts)if(z.x>=p.l&&z.x<=p.r)z.y=p.y}g.ship={x:1600,y:110,vx:rnd(-6,6),vy:0,a:rnd(-.04,.04),omega:0,thrust:0};g.zoom=1;g.cameraX=1120;g.cameraY=0;g.rest=0}
function height(x){let i=clamp(Math.floor(x/25),0,g.pts.length-2),a=g.pts[i],b=g.pts[i+1];return a.y+(b.y-a.y)*(x-a.x)/25}generate();
function finish(p){let s=g.ship,v=Math.abs(s.vy),h=Math.abs(s.vx),a=Math.abs(s.a*180/Math.PI);if(p&&v<=20&&h<=15&&a<=24){let pts=(v<=9&&h<=7&&a<=9?100:v<=14&&h<=11&&a<=16?75:40)*p.m;score(pts);g.fuel=Math.min(2000,g.fuel+35*p.m);g.msg='LANDED  '+p.m+'X  +'+pts;s.y=p.y-20;s.vx=s.vy=0;s.a=0;s.omega=0}else{spark(g.fx,s.x,s.y,23);g.msg='CRASH'}g.rest=2.2;s.thrust=0;s.vx=s.vy=0}
g.key=k=>{};g.pointer=(x,y)=>{if(x<W*.3)held.add('ArrowLeft');else if(x>W*.7)held.add('ArrowRight');else held.add('ArrowUp')};
g.update=dt=>{g.fx=stepParticles(g.fx,dt);let s=g.ship;if(g.rest>0){g.rest-=dt;if(g.rest<=0){if(g.fuel<=0)state='gameover';else{g.mission++;generate()}}return}let turn=(held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0);s.omega+=turn*5.8*dt;if(!turn)s.omega*=Math.pow(.9,dt*60);s.omega=clamp(s.omega,-2.25,2.25);s.a=clamp(s.a+s.omega*dt,-Math.PI,Math.PI);let alt=Math.max(0,height(s.x)-(s.y+20));if(alt<220&&!turn)s.omega-=s.a*1.9*dt;let power=held.has('Space')?1:held.has('ArrowUp')?(held.has('ShiftLeft')||held.has('ShiftRight')?1:.74):0;if(held.has('Space'))s.omega-=s.a*8*dt;if(g.fuel<=0)power=0;s.thrust=power;g.fuel=Math.max(0,g.fuel-(14+power*24)*power*dt-(held.has('Space')?12*dt:0));s.vx+=Math.sin(s.a)*56*power*dt;s.vy+=(GY-Math.cos(s.a)*56*power)*dt;s.x=clamp(s.x+s.vx*dt,0,GW);s.y+=s.vy*dt;
let pad=g.pads.find(p=>s.x>p.l+3&&s.x<p.r-3);if(s.y+20>=height(s.x))finish(p);let t=clamp(1-alt/300,0,1),target=1+1.05*t*t*(3-2*t);g.zoom+=(target-g.zoom)*Math.min(1,dt*3.2);let cx=clamp(s.x-W/(2*g.zoom),0,GW-W/g.zoom),cy=Math.max(0,s.y-H*.34/g.zoom);g.cameraX+=(cx-g.cameraX)*Math.min(1,dt*5);g.cameraY+=(cy-g.cameraY)*Math.min(1,dt*4.5)};
const X=x=>(x-g.cameraX)*g.zoom,Y=y=>(y-g.cameraY)*g.zoom;
g.draw=()=>{c.strokeStyle='#fff';c.lineWidth=1.5;c.beginPath();for(let i=0;i<g.pts.length;i++){let z=g.pts[i];i?c.lineTo(X(z.x),Y(z.y)):c.moveTo(X(z.x),Y(z.y))}c.stroke();for(const p of g.pads){c.lineWidth=3;line(X(p.l),Y(p.y),X(p.r),Y(p.y));c.fillStyle='#fff';txt(p.m+'X',X(p.x),Y(p.y)+20,15,'center')}let s=g.ship;c.save();c.translate(X(s.x),Y(s.y));c.scale(g.zoom,g.zoom);c.rotate(s.a);c.beginPath();c.moveTo(-12,-8);c.lineTo(-5,-17);c.lineTo(5,-17);c.lineTo(12,-8);c.lineTo(10,8);c.lineTo(-10,8);c.closePath();c.stroke();line(-8,7,-19,20);line(8,7,19,20);line(-24,20,-14,20);line(14,20,24,20);if(s.thrust){line(-5,9,0,11+rnd(14,29)*s.thrust);line(0,11+rnd(14,29)*s.thrust,5,9)}if(held.has('ArrowLeft'))line(10,-6,22,-6);if(held.has('ArrowRight'))line(-10,-6,-22,-6);c.restore();c.save();c.translate(-g.cameraX*g.zoom,-g.cameraY*g.zoom);c.scale(g.zoom,g.zoom);drawParticles(g.fx);c.restore();hud(g,'LUNAR LANDER · MISSION '+g.mission,'FUEL '+Math.floor(g.fuel)+'   ALT '+Math.max(0,Math.floor(height(s.x)-s.y-20))+'   H '+s.vx.toFixed(1)+'   V '+s.vy.toFixed(1)+'   ZOOM '+g.zoom.toFixed(2)+'X');if(g.rest>0)txt(g.msg,W/2,160,30,'center')};return g}
function makeMoon(){let g={score:0,lives:3,stage:1,x:0,speed:150,bug:{x:175,y:504,vy:0,inv:2},obs:[],ufos:[],bul:[],up:[],bad:[],fx:[],spawn:.8,ut:4,msg:'',mt:0,resp:0,jumping:false};const floor=504;
function jump(){if(g.bug.vy===0&&g.bug.y>=floor&&g.resp<=0){g.bug.vy=-370;g.jumping=true;sound(260)}}function shoot(up=false){let arr=up?g.up:g.bul;if(arr.length>5)return;arr.push({x:g.bug.x+28,y:g.bug.y-20,vx:up?0:510,vy:up?-490:0,t:1.7});sound(720)}function hit(){if(g.bug.inv>0||g.resp>0)return;g.lives--;spark(g.fx,g.bug.x,g.bug.y,22);g.resp=1.5;g.bug.inv=2;if(g.lives<=0)state='gameover'}
g.key=k=>{if(k==='Space'||k==='ArrowUp')jump();if(k==='KeyZ')shoot();if(k==='KeyX')shoot(true)};g.pointer=(x,y)=>{if(x<440)jump();else if(y<310)shoot(true);else shoot()};
g.update=dt=>{g.fx=stepParticles(g.fx,dt);if(g.resp>0){g.resp-=dt;if(g.resp<=0){g.bug.y=floor;g.bug.vy=0}return}g.x+=g.speed*dt;g.bug.inv=Math.max(0,g.bug.inv-dt);g.bug.vy+=780*dt;g.bug.y+=g.bug.vy*dt;if(g.bug.y>=floor){g.bug.y=floor;g.bug.vy=0;g.jumping=false}g.spawn-=dt;if(g.spawn<=0){let types=['rock','rock','crater','mine'];let type=types[Math.floor(rnd(0,types.length))];g.obs.push({x:1030,type,w:type==='crater'?100:type==='rock'?35:27,h:type==='rock'?36:22});g.spawn=rnd(.95,1.6)*Math.max(.65,1-g.stage*.04)}for(const o of g.obs){o.x-=g.speed*dt;if(g.bug.inv<=0&&Math.abs(o.x-g.bug.x)<(o.w/2+20)){if(o.type==='crater'){if(g.bug.y>=floor-15)hit()}else if(g.bug.y>floor-o.h+8)hit()}}g.obs=g.obs.filter(o=>o.x>-140&&!o.dead);
g.ut-=dt;if(g.ut<=0){g.ufos.push({x:1020,y:rnd(100,300),phase:rnd(0,7),t:1.2});g.ut=rnd(3,5)}for(const u of g.ufos){u.x-=175*dt;u.phase+=dt;u.y+=Math.sin(u.phase*3)*20*dt;u.t-=dt;if(u.t<=0){u.t=rnd(1,2);let a=Math.atan2(g.bug.y-u.y,g.bug.x-u.x);g.bad.push({x:u.x,y:u.y,vx:Math.cos(a)*230,vy:Math.sin(a)*230,t:3})}if(u.x<-50)u.dead=true}g.ufos=g.ufos.filter(u=>!u.dead);
for(const b of [...g.bul,...g.up,...g.bad]){b.x+=b.vx*dt;b.y+=b.vy*dt;b.t-=dt;if(g.bad.includes(b)){if(g.bug.inv<=0&&d(b.x,b.y,g.bug.x,g.bug.y-15)<24){b.t=0;hit()}}else{for(const u of g.ufos)if(!u.dead&&d(b.x,b.y,u.x,u.y)<26){u.dead=true;b.t=0;score(150);spark(g.fx,u.x,u.y)}for(const o of g.obs)if(!o.dead&&o.type!=='crater'&&Math.abs(b.x-o.x)<o.w*.55&&Math.abs(b.y-(548-o.h/2))<o.h){o.dead=true;b.t=0;score(50);spark(g.fx,o.x,548-o.h/2)}}}g.bul=g.bul.filter(b=>b.t>0&&b.x<980);g.up=g.up.filter(b=>b.t>0&&b.y>0);g.bad=g.bad.filter(b=>b.t>0);g.ufos=g.ufos.filter(u=>!u.dead);g.obs=g.obs.filter(o=>!o.dead);if(g.x>=g.stage*2500){g.stage++;g.speed+=13;score(500);g.msg='CHECKPOINT · STAGE '+g.stage;g.mt=2}g.mt=Math.max(0,g.mt-dt)};
g.draw=()=>{c.fillStyle='#132037';c.fillRect(0,0,W,H);c.strokeStyle='#8797be';for(let z=0;z<2;z++){let shift=g.x*(z?.3:.12);c.beginPath();for(let x=0;x<=1000;x+=50){let y=375+z*65-Math.abs(Math.sin((x+shift)*.008))*55;i(x,y)}c.stroke();function i(x,y){if(x===0)c.moveTo(x,y);else c.lineTo(x,y)}}c.fillStyle='#dde7ff';c.beginPath();c.arc(760,130,39,0,7);c.strokeStyle='#dde7ff';c.stroke();ground();for(const o of g.obs){c.strokeStyle='#f1f5ff';if(o.type==='crater'){c.beginPath();c.moveTo(o.x-o.w/2,548);c.quadraticCurveTo(o.x,586,o.x+o.w/2,548);c.stroke()}else{c.beginPath();c.moveTo(o.x-o.w/2,548);c.lineTo(o.x-10,548-o.h);c.lineTo(o.x+9,552-o.h);c.lineTo(o.x+o.w/2,548);c.closePath();c.stroke()}}for(const u of g.ufos){c.beginPath();c.moveTo(u.x-23,u.y);c.lineTo(u.x-10,u.y-10);c.lineTo(u.x+10,u.y-10);c.lineTo(u.x+23,u.y);c.lineTo(u.x+10,u.y+7);c.lineTo(u.x-10,u.y+7);c.closePath();c.stroke()}for(const b of [...g.bul,...g.up,...g.bad]){c.fillStyle='#fff';c.fillRect(b.x-2,b.y-2,5,5)}if(g.resp<=0&&Math.floor(g.bug.inv*11)%2===0){let b=g.bug;c.strokeStyle='#fff';c.strokeRect(b.x-28,b.y-26,60,25);c.strokeRect(b.x-4,b.y-39,17,13);for(let x of [-20,20]){c.beginPath();c.arc(b.x+x,b.y+7,9,0,7);c.stroke()}line(b.x+30,b.y-19,b.x+45,b.y-19);line(b.x+5,b.y-40,b.x+5,b.y-52)}drawParticles(g.fx);hud(g,'MOON PATROL · STAGE '+g.stage,'LIVES '+g.lives+'   DISTANCE '+Math.floor(g.x/10)+'   SPACE JUMP · Z FORWARD · X UP');if(g.mt>0)txt(g.msg,W/2,145,26,'center')};return g}
const games={icbm:{name:'ICBM 城市防禦',info:'點擊天空攔截飛彈 · 空白鍵向畫面中央射擊',make:makeICBM},asteroids:{name:'ASTEROIDS 1979',info:'← → 旋轉 · ↑ 推進 · Space 射擊 · H 超空間',make:makeAsteroids},'computer-space':{name:'COMPUTER SPACE 1971',info:'← → 旋轉 · ↑ 推進 · Space 射擊（飛彈可轉向）',make:makeComputer},'lunar-lander':{name:'LUNAR LANDER 1979',info:'← → 旋轉 · ↑ 推進 · Shift+↑ 最大推力 · Space 緊急拉升',make:makeLunar},'moon-patrol':{name:'MOON PATROL 1982',info:'Space 跳躍 · Z 前方射擊 · X 對空射擊',make:makeMoon}};
const selected=games[ID]||games.icbm;document.title=selected.name+' | 經典街機';document.getElementById('instructions').textContent=selected.info;
function restart(){game=selected.make();state='playing';held.clear();sound(440,.08)}
function input(k){sound(480,.015);if(k==='KeyR'){restart();return}if(k==='KeyP'){state=state==='playing'?'paused':state==='paused'?'playing':state;return}if(state==='title'||state==='gameover'){restart();return}if(state==='playing'&&game.key)game.key(k)}
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!held.has(e.code))input(e.code);held.add(e.code)});window.addEventListener('keyup',e=>held.delete(e.code));window.addEventListener('blur',()=>{held.clear();if(state==='playing')state='paused'});
C.addEventListener('pointerdown',e=>{e.preventDefault();let r=C.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(state==='title'||state==='gameover'){restart();return}if(state==='playing'&&game.pointer)game.pointer(x,y)});C.addEventListener('pointerup',()=>{held.delete('ArrowLeft');held.delete('ArrowRight');held.delete('ArrowUp')});
const touch=document.getElementById('touch');for(const [label,k] of [['◀','ArrowLeft'],['▶','ArrowRight'],['▲','ArrowUp'],['射擊','Space'],['Z','KeyZ'],['X','KeyX'],['跳躍','Jump']]){let b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label',label);b.addEventListener('pointerdown',e=>{e.preventDefault();held.add(k);if(k==='Jump')input('Space');else input(k)});for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,()=>held.delete(k));touch.appendChild(b)};
function frame(t){let dt=Math.min(.033,(t-(last||t))/1000);last=t;c.fillStyle='#03050b';c.fillRect(0,0,W,H);if(state==='playing')game.update(dt);if(game&&state!=='title')game.draw();if(state!=='playing'){c.fillStyle='#000a';c.fillRect(0,0,W,H);c.fillStyle='#f8fbff';txt(selected.name,W/2,245,44,'center');if(state==='title'){txt(selected.info,W/2,308,16,'center');txt('點擊畫面或按 ENTER / SPACE 開始',W/2,382,22,'center')}else if(state==='paused')txt('暫停 · 按 P 繼續',W/2,345,24,'center');else{txt('GAME OVER · SCORE '+game.score,W/2,326,24,'center');txt('點擊畫面或按 R 重新開始',W/2,378,18,'center')}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();