(function(){
'use strict';
document.addEventListener('dblclick',function(e){e.preventDefault()},{passive:false});
document.addEventListener('gesturestart',function(e){e.preventDefault()},{passive:false});
var day=1,fish=100,weight=20,score=0,oxygen=6,temp=28,sal=15,feedDone=0,waterDone=0,running=false;
var board={highScore:{name:'尚未有人上榜',score:0,date:''},top10:[]};
var apiUrl=(window.XIAOYUGE_SCORE_API||'').trim();
function E(id){return document.getElementById(id)}
function fit(){document.documentElement.style.setProperty('--vh',(window.visualViewport?window.visualViewport.height:window.innerHeight)+'px')}
fit();window.addEventListener('resize',fit);if(window.visualViewport)window.visualViewport.addEventListener('resize',fit);
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function rnd(a,b){return a+Math.random()*(b-a)}
function say(t){E('msg').textContent=t}
function saturationDO(T,S){var v=14.6244-0.367134*T+0.0044972*T*T-0.0966*S+0.00205*S*T+0.0002739*S*S;return clamp(v,4,14.7)}
function bar(id,v,min,max,g1,g2){var p=clamp((v-min)/(max-min)*100,0,100),b=E(id);b.style.width=p+'%';b.style.background=(v>=g1&&v<=g2)?'#65a965':((v<g1*.8||v>g2*1.02)?'#d66056':'#e8aa3d')}
function fishEls(){return document.querySelectorAll('.fish')}
function growFish(){var size=clamp(30+weight/9,32,78),f=fishEls();for(var i=0;i<f.length;i++)f[i].style.setProperty('--fs',(size+i*1.2)+'px')}
function pulse(cls){var f=fishEls();for(var i=0;i<f.length;i++){f[i].classList.add(cls);(function(x){setTimeout(function(){x.classList.remove(cls)},800)})(f[i])}}
function draw(){var sat=saturationDO(temp,sal);oxygen=Math.min(oxygen,sat);E('day').textContent=day;E('fishN').textContent=fish;E('weight').textContent=Math.round(weight)+'g';E('score').textContent=Math.max(0,Math.round(score));E('doT').textContent=oxygen.toFixed(1)+' / '+sat.toFixed(1);E('tempT').textContent=temp.toFixed(1);E('salT').textContent=sal.toFixed(0);bar('doB',oxygen,0,sat,5,Math.max(5,sat));bar('tempB',temp,20,36,26,30);bar('salB',sal,0,35,8,25);growFish()}
function updateRecord(){var h=board.highScore||{};E('champName').textContent=h.name||'尚未有人上榜';E('champScore').textContent=Number(h.score||0)}
async function loadBoard(){try{var url=apiUrl?apiUrl:('scores.json?t='+Date.now());var r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('load failed');var d=await r.json();if(d.highScore)board.highScore=d.highScore;if(Array.isArray(d.top10))board.top10=d.top10;updateRecord()}catch(e){try{var local=JSON.parse(localStorage.getItem('xiaoyugeHighScore')||'null');if(local&&local.score>Number(board.highScore.score||0)){board.highScore=local;board.top10=[local]}}catch(_e){}updateRecord()}}
function addFx(cls,text,left,top,life){var d=document.createElement('div');d.className=cls;if(text)d.textContent=text;if(left!=null)d.style.left=left;if(top!=null)d.style.top=top;E('fx').appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d)},life||1000)}
function feedAnim(){for(var i=0;i<20;i++)setTimeout(function(){addFx('pellet','•',(12+Math.random()*74)+'%',null,1000)},i*25);pulse('eat')}
function aerateAnim(){addFx('wheel','⚙️',null,null,1500);for(var i=0;i<32;i++)setTimeout(function(){var z=7+Math.random()*11,d=document.createElement('i');d.className='bubble';d.style.width=z+'px';d.style.height=z+'px';d.style.left=(8+Math.random()*28)+'%';d.style.top=(58+Math.random()*12)+'%';E('fx').appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d)},1900)},i*45)}
function waterAnim(){for(var i=0;i<7;i++)setTimeout(function(){addFx('flow','💧',null,(32+Math.random()*20)+'%',1100)},i*70);addFx('flash','',null,null,500)}
function checkAnim(){addFx('flash','',null,null,500)}
function nextAnim(){addFx('sunrise','',null,null,1100)}
function start(){day=1;fish=100;weight=20;score=0;oxygen=6;temp=28;sal=15;feedDone=0;waterDone=0;running=true;E('overlay').style.display='none';say('第 1 天：先看水質。28℃、15 ppt 時，溶氧飽和上限約 '+saturationDO(temp,sal).toFixed(1)+' mg/L。');draw()}
function feed(){if(!running)return;if(feedDone>=2){say('今天已餵兩次，再餵可能浪費飼料並惡化水質。');return}feedDone++;if(oxygen>=4.5){weight+=rnd(8,13);score+=12;say('餵食成功！虱目魚正在搶食。')}else{weight+=rnd(2,5);score-=5;say('溶氧偏低，魚吃得不好，先開水車。')}oxygen=Math.max(0,oxygen-.25);feedAnim();pulse('grow');draw()}
function aerate(){if(!running)return;var sat=saturationDO(temp,sal),gap=sat-oxygen;aerateAnim();if(gap<=.08){oxygen=Math.min(oxygen,sat);score+=1;say('水車持續運轉，但已接近目前飽和上限 '+sat.toFixed(1)+' mg/L；再增加水車也不會把溶氧推到 9 mg/L。')}else{var gain=Math.min(1.0,Math.max(.15,gap*.45));oxygen=Math.min(sat,oxygen+gain);score+=gain>.25?6:2;say('水車增氧 +'+gain.toFixed(1)+' mg/L；目前 '+temp.toFixed(1)+'℃、'+sal.toFixed(0)+' ppt 的飽和上限約 '+sat.toFixed(1)+' mg/L。')}draw()}
function water(){if(!running)return;if(waterDone){say('今天已換過水，避免過度換水造成波動。');return}waterDone=1;sal=clamp(sal+rnd(-2,2),0,35);temp+=(28-temp)*.35;var sat=saturationDO(temp,sal);oxygen=Math.min(sat,oxygen+.45);score+=5;waterAnim();say('換水完成。新水溫與鹽度決定新的溶氧飽和上限：約 '+sat.toFixed(1)+' mg/L。');draw()}
function check(){if(!running)return;checkAnim();var sat=saturationDO(temp,sal),pct=Math.round(oxygen/sat*100),t=[];t.push('飽和上限 '+sat.toFixed(1)+' mg/L，目前 '+pct+'% 飽和');t.push(oxygen<5?'溶氧偏低，建議開水車':'溶氧正常');t.push(temp<26?'水溫偏低':temp>30?'水溫偏高，且溶氧上限會下降':'水溫適合');t.push(sal<8||sal>25?'鹽度波動較大':'鹽度穩定');say('水質報告：'+t.join('；')+'。')}
function next(){if(!running)return;nextAnim();var healthy=true;if(oxygen<4){var loss=Math.ceil(rnd(3,8));fish=Math.max(0,fish-loss);score-=loss*8;healthy=false;say('昨晚缺氧，損失 '+loss+' 尾魚！')}else if(oxygen<5){fish=Math.max(0,fish-1);score-=4;healthy=false}if(temp<24||temp>33){var l=Math.ceil(rnd(1,4));fish=Math.max(0,fish-l);score-=l*5;healthy=false}if(feedDone===0){score-=5;healthy=false}else score+=5;if(healthy)score+=12;day++;feedDone=0;waterDone=0;oxygen=Math.max(0,oxygen-rnd(.45,.85));temp=clamp(temp+rnd(-1.2,1.5),22,35);sal=clamp(sal+rnd(-1.7,1.7),0,35);if(Math.random()<.22){var e=Math.random();if(e<.34){temp=clamp(temp+rnd(2,3.5),22,36);say('☀️ 炎熱天氣，水溫升高，溶氧飽和上限也下降！')}else if(e<.67){oxygen=Math.max(0,oxygen-rnd(.8,1.4));say('🌥️ 氣壓變化，溶氧下降，記得巡池。')}else{sal=clamp(sal-rnd(3,5),0,35);say('🌧️ 下雨後鹽度下降，注意水質。')}}else if(day<=20)say('第 '+day+' 天開始，先看水質再操作。');oxygen=Math.min(oxygen,saturationDO(temp,sal));if(day>20||fish<=0){finish();return}draw()}
function leaderboardRows(){var rows=Array.isArray(board.top10)?board.top10:[];if(!rows.length)return '<p>目前還沒有排行榜紀錄。</p>';var out='<table class="leaderboard"><tr><th>名次</th><th>姓名</th><th>分數</th><th>日期</th></tr>';for(var i=0;i<rows.length;i++){var r=rows[i]||{};out+='<tr><td>'+(i+1)+'</td><td class="n"></td><td>'+Number(r.score||0)+'</td><td>'+(r.date||'')+'</td></tr>'}return out+'</table>'}
function fillLeaderboardNames(){var cells=E('overlay').querySelectorAll('.leaderboard .n'),rows=board.top10||[];for(var i=0;i<cells.length;i++)cells[i].textContent=(rows[i]&&rows[i].name)||''}
function showLeaderboard(){if(running)return;E('overlay').style.display='flex';E('overlay').innerHTML='<div class="dialog"><div class="icon">🏆</div><h2>Top 10 排行榜</h2>'+leaderboardRows()+'<button id="closeRank" class="secondary" type="button">關閉</button></div>';fillLeaderboardNames();E('closeRank').onclick=function(){location.reload()}}
async function submitHighScore(finalScore){var input=E('winnerName'),status=E('saveStatus'),btn=E('saveWinner');var name=(input.value||'').replace(/[<>]/g,'').trim().slice(0,12);if(!name){status.textContent='請輸入姓名';input.focus();return}btn.disabled=true;status.textContent='正在儲存…';var entry={name:name,score:finalScore,date:new Date().toISOString().slice(0,10)};try{localStorage.setItem('xiaoyugeHighScore',JSON.stringify(entry))}catch(_e){}if(!apiUrl){board.highScore=entry;board.top10=[entry].concat(board.top10||[]).sort(function(a,b){return Number(b.score||0)-Number(a.score||0)}).slice(0,10);updateRecord();status.textContent='已先儲存在這台裝置；線上 GitHub 排行榜等待後端連線。';btn.textContent='已暫存';return}try{var r=await fetch(apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name,score:finalScore})});var d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'儲存失敗');if(d.highScore)board.highScore=d.highScore;if(Array.isArray(d.top10))board.top10=d.top10;updateRecord();status.textContent=d.newHigh?'✅ 新紀錄已儲存到 GitHub！':'已有更高的新紀錄，排行榜已更新。';btn.textContent='已儲存'}catch(err){status.textContent='線上儲存暫時失敗，已保留在這台裝置。';btn.disabled=false}}
function finish(){running=false;var finalScore=Math.max(0,Math.round(score+fish*2+weight*.5)),grade=finalScore>=650?'🏆 漁場達人':finalScore>=500?'🥇 養殖高手':finalScore>=350?'🥈 穩定經營':'🥉 再接再厲';var oldHigh=Number((board.highScore&&board.highScore.score)||0),isHigh=finalScore>oldHigh;E('overlay').style.display='flex';if(isHigh){E('overlay').innerHTML='<div class="dialog"><div class="icon">🏆🎉</div><h2>新最高分！</h2><p>'+grade+'<br>存活：<b>'+fish+'</b> 尾　平均重量：<b>'+Math.round(weight)+'g</b><br>總分：<b style="font-size:28px;color:#c57c16">'+finalScore+'</b></p><p>留下你的姓名，成為小宇哥漁場紀錄保持人：</p><input id="winnerName" class="nameInput" maxlength="12" autocomplete="off" inputmode="text" placeholder="請輸入姓名"><br><button id="saveWinner" class="start" type="button">儲存最高分</button><div id="saveStatus" class="saveStatus"></div><button id="again" class="secondary" type="button">再養一池</button></div>';E('saveWinner').onclick=function(){submitHighScore(finalScore)};E('again').onclick=function(){location.reload()};setTimeout(function(){E('winnerName').focus()},250)}else{E('overlay').innerHTML='<div class="dialog"><div class="icon">🐟🎉</div><h2>'+grade+'</h2><p>20 天養殖完成！<br>存活：<b>'+fish+'</b> 尾<br>平均重量：<b>'+Math.round(weight)+'g</b><br>總分：<b style="font-size:27px;color:#2f95a6">'+finalScore+'</b><br>目前最高：<b>'+oldHigh+'</b> 分</p><button id="showRank" class="start" type="button">查看排行榜</button><br><button id="again" class="secondary" type="button">再養一池</button></div>';E('showRank').onclick=showLeaderboard;E('again').onclick=function(){location.reload()}}}
E('start').onclick=start;E('feed').onclick=feed;E('aerate').onclick=aerate;E('water').onclick=water;E('check').onclick=check;E('next').onclick=next;E('rankBtn').onclick=showLeaderboard;draw();loadBoard();
})();
